### ISSUE TITLE
Move epoch lock to memory

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/shadow#104]
## Desc

Store the epoch lock into memory is better than using a lock file.

```rust
let mut epoch_lock = Arc::new(Mutex::new(Vec<usize>));

thread::join(
  runner.start(x, Arc::clone(epoch_lock)), 
  epoch(Arc::clone(epoch_lock)),
)?;
```

---

#102

**Comment by HackFisher** [comment]
@xiaoch05 This issue has high priority

**Comment by xiaoch05** [comment]
Yes I will resolve it soon.
moving the process to an independent thread or coroutine, and use memory lock.
I find this pr https://github.com/darwinia-network/shadow/pull/124 also add thread for epoch process. So I want to check the PR first.
