### ISSUE TITLE
pkg::shadow::] no such host on http request, does not support http

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/shadow#109]
```
pkg::shadow::] Post https://http//darwinia-shadow-geth-testnet: dial tcp: lookup http on 10.35.240.10:53: no such hos

```

[long_text_2020-11-04-15-27-16.txt](https://github.com/darwinia-network/shadow/files/5486140/long_text_2020-11-04-15-27-16.txt)

**Comment by HackFisher** [comment]
```
[2020-11-04T07:32:22Z ERROR pkg::shadow::] Post "https://http//localhost:8545": dial tcp: lookup http on 169.254.169.254:53: no such host
```

**Comment by HackFisher** [comment]
Must be here:

https://github.com/darwinia-network/shadow/blob/7ec094467d8bb4782b1f812e39da4cd95356d721/pkg/shadow/eth/receipt.go#L58

**Comment by clearloop** [comment]
@freehere107

**Comment by freehere107** [comment]
@clearloop providers.NewHTTPProvider third param is SSL flag, you need to check RPC URL  protocol

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/shadow/pull/110
