### ISSUE TITLE
log is unreasonable

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/shadow#113]
https://github.com/darwinia-network/shadow/blob/22fd6f90b3f60d296589a3f2fac22e40c570f72f/pkg/shadow/ffi/mod.go#L62

it should be n%1000==0

**Comment by HackFisher** [comment]
@clearloop Would you please give comments on this?

**Comment by clearloop** [comment]
> https://github.com/darwinia-network/shadow/blob/22fd6f90b3f60d296589a3f2fac22e40c570f72f/pkg/shadow/ffi/mod.go#L62
> 
> it should be n%1000==0

@xiaoch05  is correct, it should be `%`.
