### ISSUE TITLE
Move receipt proof to rust

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/shadow#114]
## Desc

Rust can generate receipt proof as well, remove the verbose go code

**Comment by xiaoch05** [comment]
expect receipt-proof, we leave `import` and `ethash-proof` features using go code. should we remove them too?
@HackFisher

**Comment by HackFisher** [comment]
> except receipt-proof, we leave `import` and `ethash-proof` features using go code. should we remove them too?
> 
> @HackFisher 

Not now, let's keep ethash-proof go lib as it is.
