### ISSUE TITLE
ropsten leaf checking

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/shadow#118]
https://testnet.shadow.darwinia.network/ethereum/mmr_leaf/9016521 这个leaf对不上了

**Comment by clearloop** [comment]
https://ropsten.etherscan.io/block/9016521/f

**Comment by clearloop** [comment]
Trying to open another thread to check and reorg the MMR store.

**Comment by HackFisher** [comment]
Related #111

**Comment by HackFisher** [comment]
https://ropsten.etherscan.io/block/9016521/f
