### ISSUE TITLE
Question and Feature Request: -v or RUST_LOG, which one is prioritized?

### ISSUE THREAD

**Issue by wi1dcard** [darwinia-network/shadow#142]
Since we have both the CLI option `-v` and the environment variable `RUST_LOG`, I'm wondering which one is prioritized?

It is also a bit confusing when `GO_LOG`, `RUST_LOG`, and `-v` exists at the same time, what is the precise log level? What should users do if they want to remove certain log lines in the future?

I think it would be nice if we have one way and only one way to change the log level. Instead of having the option `-v` or `--debug`, I personally prefer using an option or env like `--log-level` which is very precise and clear to users which level they set.

**Comment by HackFisher** [comment]
Duplicate with #161
