### ISSUE TITLE
Ethereum Classic has sampe genesis header with Ethereum? genesis header is not enough to decide network

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/shadow#151]
https://github.com/darwinia-network/shadow/blob/a0ef546b096a0a91eb34b96049d39ce5c92fa2b5/src/mmr/runner.rs#L83

**Comment by AlexChien** [comment]
Initializing a forked chain with G point to the fork block or G point set to the genesis block but with a confirmed block set to the fork block should solve the problem.  Every time a block is confirmed, it becomes the base block for retroactive check.

Alex Chien
