### ISSUE TITLE
elem in mmr are not Headers, they are just Hash(H256)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/shadow#33]
https://github.com/darwinia-network/shadow/blob/68d4fa65af14f7359f9b65888712e36c6cafd596/mmr/store.rs#L103

Please fix this.

**Comment by clearloop** [comment]
This is not a BUG, please check this:

https://github.com/darwinia-network/shadow/blob/68d4fa65af14f7359f9b65888712e36c6cafd596/mmr/store.rs#L79

SQLite can not store H256

**Comment by clearloop** [comment]
Please re-open this issue if still have questions.
