### ISSUE TITLE
rpos should be equal to the_count in store append

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/shadow#34]
https://github.com/darwinia-network/shadow/blob/68d4fa65af14f7359f9b65888712e36c6cafd596/mmr/store.rs#L98

Refer:

https://github.com/darwinia-network/darwinia-common/blob/24675358785e8c2180d560f98e404d503c557271/frame/header-mmr/src/lib.rs#L155

**Comment by clearloop** [comment]
Fixed in #31
