### ISSUE TITLE
How to fix the database if shadow service broken at some time?

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/shadow#35]
## Desc

We should consider this situation, the data size of Ethereum(and any other chain in the future) block headers are too big, some times it is a tough work to recover our data.

### 1. Some broken block was inserted into the database

+ More checks while inserting data into the database
+ Tools for Repairing the database
  + ...
+ How to test the code as comprehensive as possible?

### 2. Unit Tests

+ Need a test standard
+ How to write unit tests elegantly?
+ ...

### 3. Version control

+ Tables of Database should not be changed casually after the first stable version

### 1. The database is removed accidentally

+ Shortcut for database
+ Use remote database

### 2. ...

---

Any ideas? @wi1dcard @freehere107

**Comment by freehere107** [comment]
1. Some broken block was inserted into the database

First, make sure that the data you inserted is correct，if it is not guaranteed to be correct, please mark this incorrect data and fix it later

2. Not good at it, as long as it can cover the test is a good test

3. table can be modified, but need some migrate
4. Don't worry about this

**Comment by wi1dcard** [comment]
We'd better have a discussion about this topic @clearloop . Let's have a quick talk first on Monday and I will write down the meeting minutes (like in #30) later.
