### ISSUE TITLE
Adding extra ethereum rpc env for receipt

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/shadow#76]
https://github.com/darwinia-network/shadow#environment

Changing env after importing to support receipt is weird. 

Split ```ETHEREUM_RPC``` to ```MMR_ETHEREUM_RPC``` and ```RECEIPT_ETHEREUM_RPC```

```MMR_ETHEREUM_RPC``` support geth fast model.

```RECEIPT_ETHEREUM_RPC``` support geth full sync model or infura(with receipt), but do not support geth fast model.

@wi1dcard Currently, public node's receipt api is not working due to this.

https://testnet.shadow.darwinia.network/eth/receipt/0x1d3ef601b9fa4a7f1d6259c658d0a10c77940fa5db9e10ab55397eb0ce88807d/8610361

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/shadow/pull/77

**Comment by clearloop** [comment]
Still thinking of, the ideal way for users is using `shadow import` only for the MMR for the first time, then `shadow run` without any environment variables.

+ Generating MMRs with RPC is slow
+ The disk space of Geth node is too big that not everybody can afford it
+ Fewer settings is better

**Comment by HackFisher** [comment]
> Still thinking of, the ideal way for users is using `shadow import` only for the MMR for the first time, then `shadow run` without any environment variables.
> 
> * Generating MMRs with RPC is slow
> * The disk space of Geth node is too big that not everybody can afford it
> * Fewer settings is better

Do you need MMR_ETHEREUM_RPC for syncing after import?

Will use Infura for Ethereum Syncing? Could you make a solution description or PR for this?

**Comment by HackFisher** [comment]
shadow import support zip file or geth db, can sync using geth fast mode after import.

Do not need to support this.
