### ISSUE TITLE
Move web3 transaction listener from dj into shadow

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/shadow#84]
## Desc

Here are a lot of duplicated `proposals` executing in `darwinia-network/dj`, each dj has an Ethereum tx listener and they keep submitting duplicated `proposals` in every tx, every time.

Better to move the Ethereum tx listener into `shadow`, and just tell `DJs` which `tx/blocks` need you guys to handle.

## Design

Listen once, relay less.

### Shadow

```rust
match listen(ethereum) {
    DarwiniaTx(tx, block) => {
        clean_relay_pool_and_tx_pool();
        check_if_send_to_relay_pool(block);
        check_if_send_to_tx_pool(tx);
    }
    _ => {}
}

```

+ Add an Ethereum event listener in shadow
+ Record transactions and blocks contain Darwinia transactions
   + Clean transactions and blocks which have been confirmed in darwinia.
     + This part requires an RPC call to Darwinia in shadow, need some help of @freehere107 

### DJ

```js
setInterval(() => {
    relay(check_blocks_need_to_be_relayed());
    redeem(txes_aviable_to_redeem());
}, 10000);
```

**Comment by HackFisher** [comment]
Would like to keep shadow light and bridger decentralized, not keen in this design direction.
