### ISSUE TITLE
Cannot get ethash

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/shadow#89]
![image](https://user-images.githubusercontent.com/1070122/96845908-ceef6980-1483-11eb-9c0a-9cea2b6ee825.png)

**Comment by HackFisher** [comment]
Need testing.

@xiaoch05 Any update on this, has it already been fixed?

**Comment by xiaoch05** [comment]
@HackFisher I'm not sure what causes this problem.
But the ethash_proof process has been updated. We should have enough logs to analyze similar problems now.
