### ISSUE TITLE
Lock the network ID to the one when shadow first launched

### ISSUE THREAD

**Issue by wi1dcard** [darwinia-network/shadow#99]
RPC method: <https://eth.wiki/json-rpc/API#net_version>

If shadow can read the network ID from RPC and put it along into the DB, when it first launches (or first time writes to the DB), then the next time we run or restart shadow, if we mistakenly change the RPC endpoint to a network that doesn't match the one we previously wrote to the DB, it would be great throwing an error to notify the user instead of pushing the wrong MMR into the database. For example, `you're using the wrong RPC endpoints, expect "mainnet", actual "ropsten"`.

**Comment by xiaoch05** [comment]
We can check the `"genesis block hash"` instead of `"network ID"` when shadow launched to judge the right RPC endpoint.

**Comment by HackFisher** [comment]
Closed by #119
